#!/usr/bin/env python3
"""
Installer for Arazim Local (Linux and Windows).

It verifies privileges and dependencies (the same checks manager.py runs at
startup), copies the self-contained Arazim_Local directory to a system location,
writes the launcher there with the correct Python interpreter and manager.py
path, and exposes it as an easy entry point:

  * Linux:   deploy to /opt/Arazim_Local, symlink launcher into /usr/local/bin
             so `arazim_local` is on the PATH.
             Run: sudo python3 install/install.py
  * Windows: deploy to %ProgramData%\\ArazimLocal, copy the launcher .bat to the
             Desktop so it can be double-clicked, and add the deployed
             scripts\\Windows directory to the machine-wide PATH so
             `arazim_local` also works from any terminal.
             Run from an Administrator prompt: python install\\install.py
             (or just run it; it will prompt for elevation via UAC).
"""

import os
import platform
import shutil
import sys

# install/ lives directly under the repo root; the app is repo/Arazim_Local.
INSTALL_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(INSTALL_DIR)
SRC_DIR = os.path.join(REPO_ROOT, "Arazim_Local")

# Reuse the same privilege/dependency checks the manager uses at startup.
sys.path.append(SRC_DIR)
from utils import premissions_stats

# Skip these when copying so we deploy a clean tree.
_COPY_IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc")

LINUX_LAUNCHER_TEMPLATE = """#!/bin/bash
# Arazim Local launcher (generated by install.py).
{python} {manager} "$@"
"""

WINDOWS_LAUNCHER_TEMPLATE = """@echo off
REM Arazim Local launcher (generated by install.py).
"{python}" "{manager}" %*
"""


def _deploy(dest_dir):
    """Copy the app into dest_dir, replacing any previous install."""
    print(f"[*] Copying {SRC_DIR} -> {dest_dir}")
    if os.path.exists(dest_dir):
        shutil.rmtree(dest_dir)
    shutil.copytree(SRC_DIR, dest_dir, ignore=_COPY_IGNORE)


# Machine-wide environment block. Values written here apply to every user, and
# are picked up by processes started after the WM_SETTINGCHANGE broadcast below.
_WINDOWS_ENV_KEY = r"SYSTEM\CurrentControlSet\Control\Session Manager\Environment"


def _add_to_system_path(directory):
    """
    Append `directory` to the machine-wide PATH (HKLM), unless it is already
    there. Windows only; assumes the process is elevated (HKLM is admin-only).

    setx /M is deliberately avoided: it truncates PATH at 1024 characters and
    flattens REG_EXPAND_SZ, so the registry is edited directly and the value's
    original type is preserved.
    """
    import ctypes
    import winreg

    with winreg.OpenKey(
        winreg.HKEY_LOCAL_MACHINE, _WINDOWS_ENV_KEY, 0, winreg.KEY_READ | winreg.KEY_WRITE
    ) as key:
        try:
            current, value_type = winreg.QueryValueEx(key, "Path")
        except FileNotFoundError:
            current, value_type = "", winreg.REG_EXPAND_SZ

        # Compare literally (entries may contain %vars%; expanding them here
        # would risk baking a machine-specific path into the value we write).
        wanted = os.path.normcase(os.path.normpath(directory))
        entries = [entry for entry in current.split(";") if entry.strip()]
        for entry in entries:
            if os.path.normcase(os.path.normpath(entry.strip().strip('"'))) == wanted:
                print(f"[*] Already on the system PATH: {directory}")
                return

        entries.append(directory)
        winreg.SetValueEx(key, "Path", 0, value_type, ";".join(entries))

    # Tell already-running shells/Explorer to reload the environment block;
    # without this the new PATH only reaches processes started after a logoff.
    # SMTO_ABORTIFHUNG (0x2) keeps a hung window from stalling the installer.
    ctypes.windll.user32.SendMessageTimeoutW(
        0xFFFF, 0x001A, 0, ctypes.c_wchar_p("Environment"), 0x0002, 5000, None
    )
    print(f"[+] Added to the system PATH: {directory}")


def install_linux():
    # Same gate order as manager.py: privileges first, then dependencies. Both
    # exit on failure, so we only reach the copy once the environment is sane.
    premissions_stats.root_check()
    premissions_stats.requirements_check()

    dest_dir = "/opt/Arazim_Local"
    launcher_path = os.path.join(dest_dir, "scripts", "Linux", "arazim_local")
    manager_py = os.path.join(dest_dir, "manager", "manager.py")
    symlink_path = "/usr/local/bin/arazim_local"

    # 1. Copy the app into /opt.
    _deploy(dest_dir)

    # 2. Write the launcher (in the deployed copy) with the resolved paths.
    with open(launcher_path, "w") as f:
        f.write(LINUX_LAUNCHER_TEMPLATE.format(python=sys.executable, manager=manager_py))
    os.chmod(launcher_path, 0o755)
    print(f"[+] Launcher written: {launcher_path}")

    # 3. Symlink it into /usr/local/bin (replacing any old link).
    if os.path.islink(symlink_path) or os.path.exists(symlink_path):
        os.remove(symlink_path)
    os.symlink(launcher_path, symlink_path)
    print(f"[+] Symlinked: {symlink_path} -> {launcher_path}")

    print("[+] Installation complete. Start it with: sudo arazim_local")


def install_windows():
    # Same gate order as manager.py: privileges first (root_check triggers the
    # UAC elevation prompt if needed), then dependencies. Npcap is checked here
    # too, so a missing driver surfaces at install time rather than as a sniffer
    # crash-loop on the first run.
    premissions_stats.root_check()
    premissions_stats.requirements_check()
    premissions_stats.npcap_check()

    # Deploy under %ProgramData% (machine-wide, admin-writable, and space-free so
    # the manager's UAC self-elevation path stays clean).
    program_data = os.environ.get("ProgramData", r"C:\ProgramData")
    dest_dir = os.path.join(program_data, "ArazimLocal")
    launcher_path = os.path.join(dest_dir, "scripts", "Windows", "arazim_local.bat")
    manager_py = os.path.join(dest_dir, "manager", "manager.py")

    # 1. Copy the app into %ProgramData%\ArazimLocal.
    _deploy(dest_dir)

    # 2. Write the launcher .bat (in the deployed copy) with the resolved paths.
    with open(launcher_path, "w") as f:
        f.write(WINDOWS_LAUNCHER_TEMPLATE.format(python=sys.executable, manager=manager_py))
    print(f"[+] Launcher written: {launcher_path}")

    # 3. Copy the launcher onto the Desktop as the double-click entry point
    #    (the Windows analog of the Linux /usr/local/bin symlink).
    desktop = os.path.join(os.environ.get("USERPROFILE", ""), "Desktop")
    if os.path.isdir(desktop):
        desktop_bat = os.path.join(desktop, "arazim_local.bat")
        shutil.copyfile(launcher_path, desktop_bat)
        print(f"[+] Desktop launcher: {desktop_bat}")
    else:
        # Desktop may be redirected (e.g. OneDrive); the app is still installed.
        print(f"[!] Desktop not found at {desktop}; skipped the desktop copy.")

    # 4. Put the launcher's directory on the machine-wide PATH, so `arazim_local`
    #    is callable from any terminal (the Windows analog of /usr/local/bin).
    #    A failure here doesn't invalidate the install, so it only warns.
    try:
        _add_to_system_path(os.path.dirname(launcher_path))
    except OSError as e:
        print(f"[!] Could not update the system PATH: {e}")
        print(f"[*] Add this directory manually: {os.path.dirname(launcher_path)}")

    print("[+] Installation complete.")
    print("[*] Double-click 'arazim_local' on your Desktop, or run 'arazim_local'")
    print("    from a new Administrator terminal (open a new one to pick up PATH).")


if __name__ == "__main__":
    system = platform.system()
    if system == "Linux":
        install_linux()
    elif system == "Windows":
        install_windows()
        # Keep the (possibly UAC-elevated) console open so the user sees the result.
        input("\nPress Enter to exit...")
    else:
        sys.exit(f"[-] Unsupported OS: {system}. Supported: Linux, Windows.")
