#!/usr/bin/env python3
"""
Installer for Arazim Local (Linux and Windows).

It verifies privileges and dependencies (the same checks manager.py runs at
startup), copies the self-contained Arazim_Local directory to a system location,
writes the launcher there with the correct Python interpreter and manager.py
path, and exposes it as an easy entry point:

  * Linux:   deploy to /opt/Arazim_Local, symlink launcher into /usr/local/bin
             so `arazim_local` is on the PATH.
             Run: sudo python3 install/install.py
  * Windows: deploy to %ProgramData%\\ArazimLocal, copy the launcher .bat to the
             Desktop so it can be double-clicked.
             Run from an Administrator prompt: python install\\install.py
             (or just run it; it will prompt for elevation via UAC).
"""

import os
import platform
import shutil
import sys

# install/ lives directly under the repo root; the app is repo/Arazim_Local.
INSTALL_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(INSTALL_DIR)
SRC_DIR = os.path.join(REPO_ROOT, "Arazim_Local")

# Reuse the same privilege/dependency checks the manager uses at startup.
sys.path.append(SRC_DIR)
from utils import premissions_stats

# Skip these when copying so we deploy a clean tree.
_COPY_IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc")

LINUX_LAUNCHER_TEMPLATE = """#!/bin/bash
# Arazim Local launcher (generated by install.py).
{python} {manager} "$@"
"""

WINDOWS_LAUNCHER_TEMPLATE = """@echo off
REM Arazim Local launcher (generated by install.py).
"{python}" "{manager}" %*
"""


def _deploy(dest_dir):
    """Copy the app into dest_dir, replacing any previous install."""
    print(f"[*] Copying {SRC_DIR} -> {dest_dir}")
    if os.path.exists(dest_dir):
        shutil.rmtree(dest_dir)
    shutil.copytree(SRC_DIR, dest_dir, ignore=_COPY_IGNORE)


def install_linux():
    # Same gate order as manager.py: privileges first, then dependencies. Both
    # exit on failure, so we only reach the copy once the environment is sane.
    premissions_stats.root_check()
    premissions_stats.requirements_check()

    dest_dir = "/opt/Arazim_Local"
    launcher_path = os.path.join(dest_dir, "scripts", "Linux", "arazim_local")
    manager_py = os.path.join(dest_dir, "manager", "manager.py")
    symlink_path = "/usr/local/bin/arazim_local"

    # 1. Copy the app into /opt.
    _deploy(dest_dir)

    # 2. Write the launcher (in the deployed copy) with the resolved paths.
    with open(launcher_path, "w") as f:
        f.write(LINUX_LAUNCHER_TEMPLATE.format(python=sys.executable, manager=manager_py))
    os.chmod(launcher_path, 0o755)
    print(f"[+] Launcher written: {launcher_path}")

    # 3. Symlink it into /usr/local/bin (replacing any old link).
    if os.path.islink(symlink_path) or os.path.exists(symlink_path):
        os.remove(symlink_path)
    os.symlink(launcher_path, symlink_path)
    print(f"[+] Symlinked: {symlink_path} -> {launcher_path}")

    print("[+] Installation complete. Start it with: sudo arazim_local")


def install_windows():
    # Same gate order as manager.py: privileges first (root_check triggers the
    # UAC elevation prompt if needed), then dependencies.
    premissions_stats.root_check()
    premissions_stats.requirements_check()

    # Deploy under %ProgramData% (machine-wide, admin-writable, and space-free so
    # the manager's UAC self-elevation path stays clean).
    program_data = os.environ.get("ProgramData", r"C:\ProgramData")
    dest_dir = os.path.join(program_data, "ArazimLocal")
    launcher_path = os.path.join(dest_dir, "scripts", "Windows", "arazim_local.bat")
    manager_py = os.path.join(dest_dir, "manager", "manager.py")

    # 1. Copy the app into %ProgramData%\ArazimLocal.
    _deploy(dest_dir)

    # 2. Write the launcher .bat (in the deployed copy) with the resolved paths.
    with open(launcher_path, "w") as f:
        f.write(WINDOWS_LAUNCHER_TEMPLATE.format(python=sys.executable, manager=manager_py))
    print(f"[+] Launcher written: {launcher_path}")

    # 3. Copy the launcher onto the Desktop as the double-click entry point
    #    (the Windows analog of the Linux /usr/local/bin symlink).
    desktop = os.path.join(os.environ.get("USERPROFILE", ""), "Desktop")
    if os.path.isdir(desktop):
        desktop_bat = os.path.join(desktop, "arazim_local.bat")
        shutil.copyfile(launcher_path, desktop_bat)
        print(f"[+] Desktop launcher: {desktop_bat}")
        print("[+] Installation complete. Double-click 'arazim_local' on your Desktop.")
    else:
        # Desktop may be redirected (e.g. OneDrive); the app is still installed.
        print(f"[!] Desktop not found at {desktop}; skipped the desktop copy.")
        print(f"[+] Installation complete. Launcher: {launcher_path}")


if __name__ == "__main__":
    system = platform.system()
    if system == "Linux":
        install_linux()
    elif system == "Windows":
        install_windows()
        # Keep the (possibly UAC-elevated) console open so the user sees the result.
        input("\nPress Enter to exit...")
    else:
        sys.exit(f"[-] Unsupported OS: {system}. Supported: Linux, Windows.")
